name:deploy
  on:
    push:
      branches: [production]
  jobs:
    deploy:
      runs-on: ubuntu-latest
        steps:
          - uses: appleboy/ssh-action@v1.2.0
            with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{ secrets.EC2_USER }}
              key: ${{ secrets.EC2_SSH_KEY }}
              script: | 
                cd /var/www/bryan
                git pull origin production
